Repository Ankit404butfound/PyWhatKit, pull requests merged in 2021-11, with the labels that each got.

#134 changes as per PEP-8 and MD001
  CONTRIBUTING.md
  README.md
  pywhatkit/handwriting.py
  pywhatkit/misc.py
  pywhatkit/whats.py
Labels: documentation

#123 Version 5.2 - Update 2
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  CONTRIBUTING.md
  README.md
  pywhatkit/ascii_art.py
  pywhatkit/core/core.py
  pywhatkit/core/log.py
  pywhatkit/handwriting.py
  pywhatkit/mail.py
  pywhatkit/misc.py
  pywhatkit/sc.py
  pywhatkit/whats.py
  requirements-dev.txt
  requirements.txt
  setup.py
Labels: bug, documentation, enhancement, Setup/Config

#140 updated setup.py for version 5.2
  setup.py
Labels: Setup/Config

#142 Better Readme
  README.md
Labels: documentation

#144 Update misc.py/ added web screenshot feature
  pywhatkit/misc.py
Labels: enhancement

#146 Improved the Web Screenshot Feature
  pywhatkit/__init__.py
  pywhatkit/misc.py
Labels: enhancement
