Repository Ankit404butfound/PyWhatKit, pull requests merged in 2021-06, with the labels that each got.

#73 Formatted Code
  pywhatkit/ascii_art.py
  pywhatkit/mail.py
  pywhatkit/sc.py
Labels: enhancement

#77 Changes to requirements.txt
  requirements.txt
Labels: bug

#79 Import ImageGrab issue and lint workflow
  .github/workflows/lint.yaml
  README.md
  pywhatkit/chr_to_handwriting.py
  pywhatkit/main.py
  setup.py
Labels: bug

#80 Updated sc.py with some minor bugs
  pywhatkit/sc.py
Labels: bug, enhancement

#82 Type Hint Fixes and Updated Guidelines
  CONTRIBUTING.md
  LICENSE
  pywhatkit/ascii_art.py
  pywhatkit/chr_to_handwriting.py
  pywhatkit/exceptions.py
  pywhatkit/help.py
  pywhatkit/history.py
  pywhatkit/mail.py
  pywhatkit/main.py
  pywhatkit/sc.py
  pywhatkit/wwd.py
  setup.py
Labels: bug, documentation, enhancement

#85 Updated Download URL
  pywhatkit/main.py
  setup.py
Labels: bug, enhancement

#86 Removed take screenshot from __init__
  pywhatkit/__init__.py
Labels: bug

#87 Updated Classifiers
  setup.py
Labels: bug
