Repository Ankit404butfound/PyWhatKit, pull requests merged in 2022-01, with the labels that each got.

#164 Patch 1
  .github/ISSUE_TEMPLATE/bug_report.md
  LICENSE
  README.md
  pywhatkit/core/exceptions.py
  pywhatkit/handwriting.py
  pywhatkit/misc.py
  pywhatkit/py.typed
Labels: documentation, enhancement

#167 Added send message to group instantly to __init__.py
  pywhatkit/__init__.py
Labels: Setup/Config

#170 Update whats.py
  pywhatkit/whats.py
Labels: enhancement

#177 Fix module name mistake in Readme
  README.md
Labels: documentation

#176 Update setup.py
  setup.py
Labels: Setup/Config
